remove the discovery insertion code from AstyanaxWriter.  Admittedly, there are still CM_SPECIFIC parts in the write path, but they are isolated to one place in AlternateScribeHandler now.
This introduced one test failure that I will address on Monday:
*  ScribeHandlerIntegrationTest.testUnitPersistence:107 expected:<OK> but was:<TRY_LATER>